tab_attrs = ['name',
             'alias',
             'cached',
             'displaySource',
             'loadOrder',
             'memory',
             'multiDataSource',
             'rows',
             'schema',
             'selectedTable',
             'snapshot',
             'source',
             'staging',
             'type',
             'validated']
